version: '3'

services:
        frontend:
                build: ./react-app
                image: react-nginx:latest
                ports:
                        - "9090:80"
                volumes:
                        - frontend_volume:/var/www
                links:
                        - api
        api:
                build: ./node-app
                image: node-react-app
                ports:
                        - "1000:3000"
                volumes:
                        - backend_volume:/home/node/app
                links:
                        - mysql-development
        
        mysql-development:
                
                image: mysql:latest
                environment:
                        MYSQL_ROOT_PASSWORD: root123
                        MYSQL_DATABASE: testapp
                        MYSQL_USER: test
                        MYSQL_PASSWORD: test@123
                ports:
                        - "3308:3306"
volumes:
        frontend_volume:
        backend_volume:

